mysql:
  container_name: "mysql"
  image: mysql:5.7
  volumes:
    - .db:/var/lib/mysql
  ports:
    - "3306:3306"
  env_file:
    - .env

  environment:
    MYSQL_DATABASE: "${DB_DATABASE}"
    MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    TZ: "UTC"
